### PR TITLE
Proper path handling and fix xpsnr for windows

### PR DESCRIPTION
**Pull request by Uranite**
Fix xpsnr for windows for real this time
Fix the regex for windows

Hopefully this works on Linux

### CODE REVIEW

**Comment by trixoniisama** [comment]
We'll have to do the regex thing in stage 3 differently, this implementation causes a "division by 0" error, implying the regex failed for every for loop. Stage 1 and 2 seems to be functionning fine on Linux.

**Comment by Uranite** [comment]
Hi can you check again?

**Comment by trixoniisama** [comment]
No there's something going on with 2.5 at large, the current version of the script also has the ZeroDivisionError: division by zero error on avg_weighted = sum_weighted / count

**Comment by Uranite** [comment]
I just tried the script via ArchWSL, and I don't know why it doesn't work for you, are you using ffmpeg 7.1? If you're using custom ffmpeg 7.0 with xpsnr, can you show me one of the lines of xpsnr.log?

**Comment by trixoniisama** [comment]
> I just tried the script in this PR via ArchWSL, and I don't know why it doesn't work for you. Are you using ffmpeg 7.1?
> 
> If you're using custom ffmpeg 7.0 with xpsnr, can you show me one of the lines of xpsnr.log?

In fact, I'm running ffmpeg 6.0 compiled with xpsnr support.

This is what a line of log file looks like:
`n:    1  XPSNR Y: inf  XPSNR U: inf  XPSNR V: inf`

**Comment by trixoniisama** [comment]
Your commits seems to have more or less fixed the issue on my end, except for the fact that some frames (pure black backgrounds) sometimes have an inf score in both chroma planes which obviously makes the script fail.

**Pull request merged**
